// Generated by BUCKLESCRIPT VERSION 1.6.1, PLEASE EDIT WITH CARE
'use strict';

import * as WGLWebgl from "reasongl-web/lib/es6/src/wGLWebgl";

var Document = WGLWebgl.Document;

var createCanvas = WGLWebgl.createCanvas;

var Gl = WGLWebgl.Gl;

export {
  Document     ,
  createCanvas ,
  Gl           ,
  
}
/* WGLWebgl Not a pure module */
