// Generated by BUCKLESCRIPT VERSION 1.6.1, PLEASE EDIT WITH CARE
'use strict';

import * as Caml_int32 from "bs-platform/lib/es6/caml_int32";
import * as Pervasives from "bs-platform/lib/es6/pervasives";

function isUndefined(num) {
  return +(num === Pervasives.min_int);
}

var divideScalarByInt = Caml_int32.div;

function scalarToFloat(f) {
  return f / 100.0;
}

function $neg$dot(prim, prim$1) {
  return prim - prim$1 | 0;
}

function $plus$dot(prim, prim$1) {
  return prim + prim$1 | 0;
}

var $slash$dot = Caml_int32.div;

var $star$dot = Caml_int32.imul;

function $tilde$neg$dot(prim) {
  return -prim | 0;
}

var cssUndefined = Pervasives.min_int;

var zero = 0;

var unitsPerPixel = 100.0;

var scalarToString = Pervasives.string_of_int;

export {
  cssUndefined      ,
  isUndefined       ,
  zero              ,
  divideScalarByInt ,
  unitsPerPixel     ,
  scalarToFloat     ,
  $neg$dot          ,
  $plus$dot         ,
  $slash$dot        ,
  $star$dot         ,
  $tilde$neg$dot    ,
  scalarToString    ,
  
}
/* No side effect */
