// Generated by BUCKLESCRIPT VERSION 1.6.1, PLEASE EDIT WITH CARE
'use strict';

var WGLWebgl = require("reasongl-web/lib/js/src/wGLWebgl");

var Document = WGLWebgl.Document;

var createCanvas = WGLWebgl.createCanvas;

var Gl = WGLWebgl.Gl;

exports.Document     = Document;
exports.createCanvas = createCanvas;
exports.Gl           = Gl;
/* WGLWebgl Not a pure module */
