// Generated by BUCKLESCRIPT VERSION 1.6.1, PLEASE EDIT WITH CARE
'use strict';

var Caml_int32 = require("bs-platform/lib/js/caml_int32");
var Pervasives = require("bs-platform/lib/js/pervasives");

function isUndefined(num) {
  return +(num === Pervasives.min_int);
}

var divideScalarByInt = Caml_int32.div;

function scalarToFloat(f) {
  return f / 100.0;
}

function $neg$dot(prim, prim$1) {
  return prim - prim$1 | 0;
}

function $plus$dot(prim, prim$1) {
  return prim + prim$1 | 0;
}

var $slash$dot = Caml_int32.div;

var $star$dot = Caml_int32.imul;

function $tilde$neg$dot(prim) {
  return -prim | 0;
}

var cssUndefined = Pervasives.min_int;

var zero = 0;

var unitsPerPixel = 100.0;

var scalarToString = Pervasives.string_of_int;

exports.cssUndefined      = cssUndefined;
exports.isUndefined       = isUndefined;
exports.zero              = zero;
exports.divideScalarByInt = divideScalarByInt;
exports.unitsPerPixel     = unitsPerPixel;
exports.scalarToFloat     = scalarToFloat;
exports.$neg$dot          = $neg$dot;
exports.$plus$dot         = $plus$dot;
exports.$slash$dot        = $slash$dot;
exports.$star$dot         = $star$dot;
exports.$tilde$neg$dot    = $tilde$neg$dot;
exports.scalarToString    = scalarToString;
/* No side effect */
