// Generated by BUCKLESCRIPT VERSION 1.6.1, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives");

function pretty_print(name, param) {
  var left = param[/* left */0];
  var top = param[/* top */1];
  var right = param[/* right */2];
  var bottom = param[/* bottom */3];
  var width = param[/* width */4];
  var height = param[/* height */5];
  console.log("===============");
  console.log("     =====> " + name);
  console.log("Left: " + Pervasives.string_of_int(left));
  console.log("Top: " + Pervasives.string_of_int(top));
  console.log("Right: " + Pervasives.string_of_int(right));
  console.log("Bottom: " + Pervasives.string_of_int(bottom));
  console.log("Width: " + Pervasives.string_of_int(width));
  console.log("Height: " + Pervasives.string_of_int(height));
  console.log("===============");
  return /* () */0;
}

var css_max_cached_result_count = 6;

exports.css_max_cached_result_count = css_max_cached_result_count;
exports.pretty_print                = pretty_print;
/* No side effect */
