// Generated by BUCKLESCRIPT VERSION 1.6.1, PLEASE EDIT WITH CARE
'use strict';

var Curry         = require("bs-platform/lib/js/curry");
var Utils         = require("./utils");
var Reprocessing  = require("./reprocessing");
var Drawfunctions = require("./drawfunctions");

function setup(env) {
  Curry._3(Drawfunctions.P[/* size */17], 600, 600, env);
  Curry._2(Drawfunctions.P[/* fill */8], Curry._3(Utils.PUtils[/* color */1], 255, 0, 0), env);
  return /* record */[/* squarePos : tuple */[
            0,
            0
          ]];
}

function draw(state, env) {
  Curry._2(Drawfunctions.P[/* background */39], Curry._3(Utils.PUtils[/* color */1], 150, 255, 255), env);
  var match = state[/* squarePos */0];
  var sy = match[1];
  var sx = match[0];
  var match$1 = Curry._1(Drawfunctions.P[/* pmouse */3], env);
  var py = match$1[1];
  var px = match$1[0];
  var squarePos;
  if (Curry._1(Drawfunctions.P[/* mousePressed */4], env) && px > sx && px < (sx + 300 | 0) && py > sy && py < (sy + 300 | 0)) {
    var match$2 = Curry._1(Drawfunctions.P[/* mouse */2], env);
    var dx = match$2[0] - px | 0;
    var dy = match$2[1] - py | 0;
    squarePos = /* tuple */[
      sx + dx | 0,
      sy + dy | 0
    ];
  } else {
    squarePos = state[/* squarePos */0];
  }
  Curry._5(Drawfunctions.P[/* rect */29], squarePos[0], squarePos[1], 300, 300, env);
  return /* record */[/* squarePos */squarePos];
}

Curry.app(Reprocessing.ReProcessor[/* run */0], [
      setup,
      /* Some */[draw],
      /* None */0,
      /* None */0,
      /* None */0,
      /* None */0,
      /* None */0,
      /* None */0,
      /* None */0,
      /* () */0
    ]);

var squareWidth = 300;

var squareHeight = 300;

exports.squareWidth  = squareWidth;
exports.squareHeight = squareHeight;
exports.setup        = setup;
exports.draw         = draw;
/*  Not a pure module */
